// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	ProtoEvent
*/
package main

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ProtoEvent struct {
	Id               *string `protobuf:"bytes,1,req" json:"Id,omitempty"`
	EventType        *string `protobuf:"bytes,2,req" json:"EventType,omitempty"`
	EventData        []byte  `protobuf:"bytes,3,req" json:"EventData,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoEvent) Reset()         { *m = ProtoEvent{} }
func (m *ProtoEvent) String() string { return proto.CompactTextString(m) }
func (*ProtoEvent) ProtoMessage()    {}

func (m *ProtoEvent) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *ProtoEvent) GetEventType() string {
	if m != nil && m.EventType != nil {
		return *m.EventType
	}
	return ""
}

func (m *ProtoEvent) GetEventData() []byte {
	if m != nil {
		return m.EventData
	}
	return nil
}

func init() {
}
