// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	ProtoEvent
	IndexProto
	IndexEntryProto
*/
package main

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ProtoEvent struct {
	Id               *string `protobuf:"bytes,1,req" json:"Id,omitempty"`
	EventType        *string `protobuf:"bytes,2,req" json:"EventType,omitempty"`
	EventData        []byte  `protobuf:"bytes,3,req" json:"EventData,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ProtoEvent) Reset()         { *m = ProtoEvent{} }
func (m *ProtoEvent) String() string { return proto.CompactTextString(m) }
func (*ProtoEvent) ProtoMessage()    {}

func (m *ProtoEvent) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *ProtoEvent) GetEventType() string {
	if m != nil && m.EventType != nil {
		return *m.EventType
	}
	return ""
}

func (m *ProtoEvent) GetEventData() []byte {
	if m != nil {
		return m.EventData
	}
	return nil
}

type IndexProto struct {
	Index            []*IndexEntryProto `protobuf:"bytes,1,rep" json:"Index,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *IndexProto) Reset()         { *m = IndexProto{} }
func (m *IndexProto) String() string { return proto.CompactTextString(m) }
func (*IndexProto) ProtoMessage()    {}

func (m *IndexProto) GetIndex() []*IndexEntryProto {
	if m != nil {
		return m.Index
	}
	return nil
}

type IndexEntryProto struct {
	EventNumber      *int64 `protobuf:"varint,1,req" json:"EventNumber,omitempty"`
	Position         *int64 `protobuf:"varint,2,req" json:"Position,omitempty"`
	Length           *int64 `protobuf:"varint,3,req" json:"Length,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *IndexEntryProto) Reset()         { *m = IndexEntryProto{} }
func (m *IndexEntryProto) String() string { return proto.CompactTextString(m) }
func (*IndexEntryProto) ProtoMessage()    {}

func (m *IndexEntryProto) GetEventNumber() int64 {
	if m != nil && m.EventNumber != nil {
		return *m.EventNumber
	}
	return 0
}

func (m *IndexEntryProto) GetPosition() int64 {
	if m != nil && m.Position != nil {
		return *m.Position
	}
	return 0
}

func (m *IndexEntryProto) GetLength() int64 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

func init() {
}
